config/routes.rb
Rails.application.routes.draw do

  get '/home', to: 'main_courses#home'
  get '/buffet', to: 'static_pages#buffet'
  get '/kitchen', to: 'posts#new'
  get '/users/user_posts_feed', to: 'users#user_posts_feed'
  get '/personal_chefs', to: "static_pages#personal_chefs"
  get '/subscribers', to: 'static_pages#subscribers'
  get '/bar', to: 'static_pages#bar'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  post 'application/handle_main_course' => 'application#handle_main_course'

  post 'static_pages/handle_next' => 'static_pages#handle_next'
  post 'static_pages/handle_prev' => 'static_pages#handle_prev'
  post 'static_pages/handle_like' => 'static_pages#handle_like'
  post 'static_pages/handle_dislike' => 'static_pages#handle_dislike'

  post 'main_courses/handle_next' => 'main_courses#handle_next'
  post 'main_courses/handle_prev' => 'main_courses#handle_prev'
  post 'main_courses/handle_like' => 'main_courses#handle_like'
  post 'main_courses/handle_dislike' => 'main_courses#handle_dislike'


  post 'users/handle_next' => 'users#handle_next'
  post 'users/handle_prev' => 'users#handle_prev'
  post 'users/handle_post_like' => 'users#handle_post_like'
  post 'users/handle_post_dislike' => 'users#handle_post_dislike'
  post 'users/handle_subscribe' => 'users#handle_subscribe'
  post 'users/handle_unsubscribe' => 'users#handle_unsubscribe'

  post 'comments/handle_like' => 'comments#handle_like'
  post 'comments/handle_dislike' => 'comments#handle_dislike'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'main_courses#home'

  resources :users do
    member do
     get :posts_feed
    end

    member do
      get :subscribers
    end

    member do
      get :edit_password
    end
  end
  resources :posts
  resources :comments, except: [:show]
  resources :notifications do
    member do
      get :notification_list
    end
  end

  resources :notifications, only: [:delete]

end

app/models/user.rb
class User < ApplicationRecord

  MINIMUM_NAME_LENGTH = 6
  MAXIMUM_NAME_LENGTH = 30
  MAXIMUM_EMAIL_LENGTH = 255
  MINIMUM_PASSWORD_LENGTH = 6

  before_save { self.email = self.email.downcase }

  mount_uploader :picture, ProfilePicUploader

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed #following is the array of USERS that self is following
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower #followers is the array of USERS that self is being followed by #Allows us to say User.followers
  has_many :notifications, dependent: :destroy

  has_secure_password
  attr_accessor :remember_token

  validates :name, presence: true, length: {minimum: MINIMUM_NAME_LENGTH, maximum: MAXIMUM_NAME_LENGTH},
                                                              uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: MAXIMUM_EMAIL_LENGTH},
                              format: {with: VALID_EMAIL_REGEX},
                                  uniqueness: {case_sensitive: false}
  validates :password, presence:true, length:{minimum: MINIMUM_PASSWORD_LENGTH}, allow_nil: true

  validate :picture_size



  #Session methods
  #give this method a string and it will return a hash using the BCrypt gem
  def User.digest(string)
   cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                 BCrypt::Engine.cost
   BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token

   SecureRandom.urlsafe_base64

  end

  def remember

   self.remember_token = User.new_token

   update_attribute(:remember_digest, User.digest(remember_token))

  end

 #like authenticate method for password but we are authenticating the users token with the hashed
  #token stored in the database
  def authenticate_token(remember_token)

    #Let's say a user has two different browsers open. In one browser, the user logs out. The other browser just gets
    #closed. When the user comes back to the second browser, the user_id cookie will still be in memory and the user
    #will be attempted to be pulled out of the db. This cannot happen though because the remember_digest of the user will
    #authenticate_token method when attempting to authenticate a user using conditionals, so we can just make the method
    #return false if the remember_digest is nil

    if remember_digest.nil?
      false
    else
      BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

  end

  #you dont have to nil the remember_token for the user because it will just get reassigned anyway
  def forget

    update_attribute(:remember_digest, nil)

  end






  #Post and comment functions
  #The following two functions are for pushing and removing liked post ID's from the User model
  def pushLikedPost(postID)

    posts = self.liked_posts
    posts.push(postID)
    update_attribute(:liked_posts, posts)

  end

  def removeLikedPost(postID)

    posts = self.liked_posts
    posts.delete(postID)
    update_attribute(:liked_posts, posts)

  end

  def pushDislikedPost(postID)

    posts = self.disliked_posts
    posts.push(postID)
    update_attribute(:disliked_posts, posts)

  end

  def removeDislikedPost(postID)

    posts = self.disliked_posts
    posts.delete(postID)
    update_attribute(:disliked_posts, posts)

  end




  #The following functions are just like the ones for pushing and removing liked posts from user arrays but they are for comments
  def pushLikedComment(commentID)

    comments = self.liked_comments
    comments.push(commentID)
    update_attribute(:liked_comments, comments)

  end

  def removeLikedComment(commentID)

    comments = self.liked_comments
    comments.delete(commentID)
    update_attribute(:liked_comments, comments)

  end

  def pushDislikedComment(commentID)

    comments = self.disliked_comments
    comments.push(commentID)
    update_attribute(:disliked_comments, comments)

  end

  def removeDislikedComment(commentID)

    comments = self.disliked_comments
    comments.delete(commentID)
    update_attribute(:disliked_comments, comments)

  end



  #functions for following
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    self.following.include?(other_user) #this is possible from the has :through relationship we made
  end




  private

  def picture_size

    if picture.size > 5.megabytes

      errors.add(:picture, "should be less than 5MB")

    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UsersHelper

  before_action :post_like_dislike_filter, only: [:handle_post_like, :handle_post_dislike]
  before_action :prevent_other_user_edits, only: [:edit, :edit_password]
  before_action :if_logged_in_redirect, only:[:new]

  #User profile page will show information about user and their posts
  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts
  end

  def new
    @user = User.new

    #This is a session variable that tells us whether or not the 'Thanks for signing up modal' should appear on the user profile screen
    #I initialize it to false here and when they user is created it will be switched to true until the user clicks out
    session[:show_signup_message] = false
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def create

    @user = User.new(user_params)

    if @user.save

      #handle success
      log_in(@user) #store the user_id as the current_user id
      session[:show_signup_message] = true #show the signup message
      redirect_to @user #redirect user to his/her profile page

    else

      #handle error
      #rerender the page if the system detects an error. The corresponding view will display the errors
      render 'new'
      session[:show_signup_message] = false #make sure the modal stays false

    end
  end

  def update

    @user = User.find(params[:id])

    #In this method, each corresponding user attribute can be change depending on which submit button is pressed on the edit page
    if(params[:change_username])

      if @user.update_attributes(user_params)
        session[:show_username_changed] = true #another modal to confirm that a username update happened
        redirect_to @user
      else
        render 'edit' #if we get an error then rerender the page
      end

    end
    #each method changer in this update method is structured in the same manner as this change_username block

    if(params[:change_email])

      if @user.update_attributes(user_params)
        session[:show_email_changed] = true
        redirect_to @user
      else
        render 'edit'
      end
    end

    #edit_password is a different page from the edit page where you can update your password
    if(params[:change_password])
      if params[:user][:password].empty? #include an empty password check
        flash[:danger] = "Password fields are empty"
        render 'edit_password'
      else
        if @user.update_attributes(user_params)
          if @user.update_attributes(user_params)
            session[:show_password_changed] = true
            redirect_to @user
          else
            render 'edit_password'
          end
        else
          render 'edit_password'
        end
      end
    end

    if(!(params[:change_picture].nil?))

      if @user.update_attribute(:picture, params[:user][:picture])
        session[:show_profile_pic_changed] = true
        redirect_to @user
      else
        render 'edit'
        session[:show_profile_pic_changed] = false
      end
    end

  end

  def edit_password #separate page to let user update his/her password

    @user = User.find(params[:id])

  end

  #This is the feed for each individual user's posts (Click on a thumbnail in a user profile and this feed is what will appear)
  def posts_feed

    init_posts_feed

  end

  #When the user presses the next arrow button, the next post from the user's profile will appear on the screen
  def handle_next

    init_next

    respond_to do |format|

      format.js { render :file => 'shared/handle_next_prev.js.erb' }

    end

  end

  #When the user presses the previous arrow button, the previous post from the user's profile will appear on the screen
  def handle_prev

    init_prev

    respond_to do |format|

      format.js { render :file => 'shared/handle_next_prev.js.erb' }

    end

  end

  def handle_post_like

    #used by the like_logic function
    @poster = User.find(params[:user_id])
    @all_posts = @poster.posts
    @current_post = @all_posts[session[:currentIndex]]

    like_logic

    #notify the poster that their post was liked
    @poster.notifications.create(description:"liked your post", from_user_id: current_user.id, from_post_id: @current_post.id)

    #Use AJAX to update the like button
    respond_to do |format|
      format.js {render :file => 'users/handle_post_like_dislike.js.erb'}
    end

  end


  def handle_post_dislike

    @poster = User.find(params[:user_id])
    @all_posts = @poster.posts
    @current_post = @all_posts[session[:currentIndex]]

    dislike_logic

    #Use AJAX to update the dislike button
    respond_to do |format|
      format.js {render :file => 'users/handle_post_like_dislike.js.erb'}
    end

  end


  #users can subscribe to other users
  def handle_subscribe

    @user = User.find(params[:user_id])
    current_user.follow(@user)

    #update the subscribe button using AJAX
    respond_to do |format|
      format.js { render :file => 'users/handle_sub_unsub.js.erb' }
    end

    #notify the user when someone subscribes to them
    @user.notifications.create(description:"has subscribed to your memes!", from_user_id: current_user.id)

  end

  def handle_unsubscribe

    @user = User.find(params[:user_id])
    current_user.unfollow(@user)

    respond_to do |format|
      format.js { render :file => 'users/handle_sub_unsub.js.erb' }
    end

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture)
  end

  #Just a filter to keep non-logged-in people from liking a post
  def post_like_dislike_filter

    unless logged_in?
      redirect_to login_path
      flash[:danger] = "You must be logged in to like/dislike a post"
    end

  end

  #protect edit pages - keep anyone out who isnt the owner of the edit page
  def prevent_other_user_edits
    @user = User.find(params[:id])

    if !(logged_in?)
      redirect_to login_path
      flash[:danger] = "You must be logged in to visit this page"

    else
      if (current_user.id != @user.id)
        redirect_to home_path
        flash[:danger] = "You must be logged in as the correct user to visit this page"
      end
    end
  end

  #dont let the user visit the signup page if they are already logged in
  def if_logged_in_redirect
    if logged_in?
      redirect_to current_user
    end
  end

end

app/helpers/users_helper.rb
#module to help clean up the UsersController class
module UsersHelper

  #used with posts_feed method
  def init_posts_feed
    #Clicking on the user profile thumbnail picture will send a post_id which we will use to find and enlarge which post was clicked.
    #We use this to get the rest of the information we need to display the post, and the corresponding poster and comments.
    @current_post = Post.find_by(id: params[:post_id])
    @poster = @current_post.user
    @all_posts = @poster.posts
    @post_comments = @current_post.comments

    #I store the currentIndex of the post in a session so that the next and previous methods can know which post to go to next
    session[:currentIndex] = @all_posts.index(@current_post)

    #if the user is logged in then build a new comment that the user can use to write a new comment
    if logged_in?
      @comment = current_user.comments.build
    end

    #keeping the current_post id stored is useful if I end up needing it later
    #like in the handle_main_course function
    session[:current_post_id] = @current_post.id

  end

  #used with handle_next user function
  def init_next

    #When the next button is pressed we need to get the user id passed in through a custmo params variable because params[:id]
    #will not work.
    @poster = User.find(params[:user_id])
    #I use the session[:currentIndex] variable as an index into an array of user posts found in all_posts
    @all_posts = @poster.posts
    session[:currentIndex] = session[:currentIndex]+1 #increase the current index by 1 to get the 'next' post
    @current_post = @all_posts[session[:currentIndex]]
    @post_comments = @current_post.comments

    session[:current_post_id] = @current_post.id

  end

  #used with handle_prev user function
  def init_prev
    @poster = User.find(params[:user_id])
    @all_posts = @poster.posts
    (session[:currentIndex] = session[:currentIndex]-1) unless (session[:currentIndex] == 0) #dont go into negative index
    @current_post = @all_posts[session[:currentIndex]]
    @post_comments = @current_post.comments

    session[:current_post_id] = @current_post.id

  end

end

app/views/users/_sub_button.html.erb
<!--Subscription button partial-->

<% if current_user.following?(@user) %>
  <%= link_to({controller: "users", action:"handle_unsubscribe", user_id: @user.id },
              class: "btn btn-default subscribeProfileButton", remote: true, method: "post") do %>
                <p><b class="glyphicon glyphicon-heart"></b> Unsubscribe: <%= @user.followers.count %></p><% end %>
<% else %>
  <%= link_to({controller: "users", action: "handle_subscribe", user_id: @user.id },
        class: "btn btn-default subscribeProfileButton", remote: true, method: "post") do %>
          <p><b class="glyphicon glyphicon-heart"></b> Subscribe: <%= @user.followers.count %></p><% end %>
<% end %>

app/views/users/_user_modals.html.erb
<% if session[:show_signup_message] == true %>

  <script>BootstrapDialog.show({
            title: 'WELCOME ABOARD! :D',
            message: 'Take a seat and enjoy the delicious memes we have to offer or get in the kitchen and cook up some of your own!'
        });</script>

        <% session[:show_signup_message] = false %>

<% end %>

<% if session[:show_new_post_dialog] == true %>

  <script>BootstrapDialog.show({
            title: "Post successful",
            message: "Now that's a dope dish you dank memer"
        });</script>

        <% session[:show_new_post_dialog] = false %>

<% end %>

<% if session[:show_username_changed] == true %>

  <script>BootstrapDialog.show({
            title: "Username Updated Successfully",
            message: "Rollin' around with a new name now, huh?"
        });</script>

        <% session[:show_username_changed] = false %>

<% end %>

<% if session[:show_email_changed] == true %>

  <script>BootstrapDialog.show({
            title: "Email Updated Successfully",
            message: "Changin' your address? You hidin' somethin'?"
        });</script>

        <% session[:show_email_changed] = false %>

<% end %>

<% if session[:show_password_changed] == true %>

  <script>BootstrapDialog.show({
            title: "Password Updated Successfully",
            message: "Don't worry, we won't tell anyone."
        });</script>

        <% session[:show_password_changed] = false %>

<% end %>

<% if session[:show_profile_pic_changed] == true %>

  <script>BootstrapDialog.show({
            title: "Profile Pic Updated Successfully",
            message: "Damn, you aint as ugly as I thought you'd be"
        });</script>

        <% session[:show_profile_pic_changed] = false %>

<% end %>

app/views/users/_user_profile_header.html.erb
<!-- Upper block of each user's profile that contains all the profile functionality -->
<div class="userProfileTitle">

  <div class="media userProfileTitleMedia">
    <div class="media-left">
      <%= image_tag @user.picture.url, class: "userProfilePicture"%>
    </div>

    <div class="media-body">
      <h1 class="media-heading"><%= @user.name %></h1>
          <%= link_to({ controller:'static_pages', action:'subscribers', :user_id => @user.id},
                      class:"userProfileSubscribersLink") do %>Subscribers: <span class="profileSubCount">
                                                                    <%= @user.followers.count %></span><% end %>
    </div>

  </div>

  <!-- Dont let other users edit another user's profile or make memes for them -->
  <% if logged_in? %>
    <% if current_user.id == @user.id %>
      <%= link_to  kitchen_path, class: "btn btn-danger makeMemesProfileButton" do %>
        <p><b class="glyphicon glyphicon-fire"></b> Cook up a new Meme!</p>
        <% end %>
        <%= link_to  edit_user_path(@user), class: "btn btn-default settingsProfileButton" do %>
        <p><b class="glyphicon glyphicon-cog"></b> Edit Profile</p>
        <% end %>
        <%= link_to({controller:'notifications', action:'notification_list', :user_id => current_user.id},
              style:"position: absolute; top: 2%; right:3%; font-weight: bold; text-decoration: none;") do %>
          <h3>
            <b class="glyphicon glyphicon-bell"></b> Notifications
            <% if(current_user.notifications.where(seen: false).count != 0) %>
              <span class="badge" style="background-color:#3366BB; font-size:0.75em;"><%= current_user.notifications.where(seen: false).count %></span>
            <% end %>
          </h3>
        <% end %>

    <% else %>
      <!-- Subscriber button - Displays how many subscribers a user have an whether or not current_user is subbed already -->
      <div class="subButton">
        <%= render 'users/sub_button' %>
      </div>
    <% end %>
  <% end %>


</div>

app/views/users/_user_profile_posts.html.erb
<!--This renders the posts on the user profile page -->
<% if @posts.any? %>
  <div class="col-md-offset-1 col-sm-offset-1">
    <% @posts.each do |post| %>
      <div class="col-md-3 col-sm-3 postThumbnail">
        <div class="thumbnail">


          <!--If this is the current_user's profile then let them delete posts -->
          <% if logged_in? %>
            <% if current_user.id == @user.id %>
              <div class="whiteCircle"> <!--Helps make sure the background of the 'X' is white-->
              </div>
              <%= link_to({controller:"posts", action:"destroy", :post_id => post.id}, class:" deleteProfilePostButton",
                method: "delete", data: {confirm: "Are you sure you want to delete your dank meme?", remote: true}) do %>
                <b class="glyphicon glyphicon-remove-sign"></b>
              <% end %>

            <% end %>
          <% end %>

          <%= link_to(posts_feed_user_path(@user, :post_id => post.id)) do %>
            <%= image_tag post.picture.url if post.picture? %>
          <% end %>
        </div>

        <div class="caption">
          <% if post.title.nil? %> <!-- Add default title just in case -->
            <h4>Dank Meme</h4>
          <% else %>
            <h4>
              <% if post.main_course %>
                <b class="glyphicon glyphicon-star"
                  style="position: absolute; right: 9%; top: 10%; color: #ffff00; font-size: 1.75em;
                  background-color: #5555ee; border-radius:25px; width: 25px; height: 25px;"></b>
              <% end %><%= post.title %>
          </h4>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/edit.html.erb
<!-- Basic edit page for user information -->
<% provide(:title, "Edit Profile") %>
<% provide(:subtitle, "Need a name change?") %>

<!-- Script code for preview generation. Credit: https://www.spencerdixon.com/blog/image-preview-with-carrierwave-and-rails.html -->
<!-- javascript image preview -->
<script>
$(function() {
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        $('#editProfilePicture').attr('src', e.target.result);
      }
      reader.readAsDataURL(input.files[0]);
    }
  }

  $("#newProfilePicture").change(function(){
    $('#editProfilePicture').removeClass('hidden');
    readURL(this);
  });
});
</script>

<div class="container">
  <div class="row">

    <div class="col-md-offset-2 col-sm-offset-2">
      <div class="editProfilePictureBlock">
        <%= image_tag(@user.picture.url, id: "editProfilePicture", class: "img-thumbnail") %>

        <%= form_for @user do |f| %>

          <%= f.file_field :picture, id:"newProfilePicture" %>
          <%= f.submit "Submit New Profile Picture",
                class:"btn btn-md btn-default", style: "margin-top: 5px;", name: 'change_picture', id:"newProfilePictureButton" %>

          <!--Script to prevent user from submitting a picture if they havnt uploaded yet -->
          <script type="text/javascript">
                $(document).ready(
                  function(){
                    $('#newProfilePictureButton').attr('disabled',true);
                    $('input:file').change(
                      function(){
                        if ($(this).val()){
                          $('#newProfilePictureButton').removeAttr('disabled');
                        }
                        else {
                          $('#newProfilePictureButton').attr('disabled',true);
                        }
                      });
                  });
          </script>

        <% end %>
      </div>
    </div>

    <div class="col-md-offset-4 col-sm-offset-5 col-md-7 col-sm-7">
      <div class="editProfileBlock">

        <h1>Edit Profile</h1>
        <%= form_for @user do |f| %>

          <%= render 'shared/error_messages', object:f.object %>

          <%= f.label :name, "New Username" %>
          <%= f.text_field :name, class: "form-control" %>

          <%= submit_tag "Submit New Username", class:"btn btn-md btn-default",
                  style: "float: right; margin-top: 5px;", name: 'change_username' %><br><br>


          <%= f.label :email, "New Email" %>
          <%= f.email_field :email, class: "form-control" %>

          <%= submit_tag "Submit New Email", class:"btn btn-md btn-default",
                  style: "float: right; margin-top: 5px;", name: 'change_email' %><br><br>

        <% end %>

        <%= link_to "Change Password", edit_password_user_path(@user), style: "display: block; float: right;" %><br>
        <%= link_to "< Back to Profile", @user, style: "display: block; float: right;" %>

        <!--<%= link_to "Change Email", "#", class: "btn btn-default btn-lg"%><br>
        <%= link_to "Change Profile Picture", "#", class: "btn btn-default btn-lg"%><br>
        <%= link_to "Change Password", "#", class: "btn btn-default btn-lg" %>-->
      </div>
    </div>
  </div>
</div>

app/views/users/edit_password.html.erb
<!-- Form to let user edit his/her password -->
<% provide(:title, "Change Password") %>
<% provide(:subtitle, "Enter new password") %>

<div class="container">
  <div class="row">

    <div class="col-md-offset-4 col-md-5 col-sm-offset-4 col-sm-5" style="margin-top: 10%;">

      <h1>Change Password</h1>

      <%= form_for @user do |f| %>

        <%= render 'shared/error_messages', object:f.object %>

        <%= f.label :password, "New Password" %>
        <%= f.password_field :password, class: "form-control" %><br>

        <%= f.label :password_confirmation, "Confirm New Password" %>
        <%= f.password_field :password_confirmation, class: "form-control" %>

        <%= submit_tag "Submit New Password", class:"btn btn-md btn-default",
                style: "float: right; margin-top: 5px;", name: 'change_password' %><br><br><br>

      <% end %>
      <%= link_to "< Back to Profile", @user, style: "display: block; float: right;" %>

    </div>

  </div>
</div>

app/views/users/handle_next_prev.js.erb
/*Used by user profile feed*/

$(function() {
  $('.postTitle').html("Dish Name: <%= @current_post.title %>");

  $('.postCaption').html("<h2><%= @current_post.description %></h2>");
  $('.mainPostImage').html("<%= escape_javascript image_tag(@current_post.picture.url, alt: "current image") if (@current_post).picture? %>");
  $('.posterPicture').html("<%= escape_javascript image_tag(@poster.picture.url, alt: "profile image", class: "img-circle") %>");

  $('.postOwner').html("<%= @poster.name %>");
  $('.linkToPosterProfile').attr("href", "<%= user_path(@poster) %>");
  $('.postTime').html("Posted <%= time_ago_in_words(@current_post.created_at) %> ago");

  //like button stuff
  $('.postLikes').html("<%= @current_post.likes %>");

  <% if @current_post.liked_by(current_user) %>
    $('.likeButtonText').html("Liked");

  <% else %>
    $('.likeButtonText').html("Like");

  <% end %>

  //dislike button stuff
  $('.postDislikes').html("<%= @current_post.dislikes %>");

  <% if @current_post.disliked_by(current_user) %>
    $('.dislikeButtonText').html("Disliked");

  <% else %>
    $('.dislikeButtonText').html("Dislike");

  <% end %>

  $('.postComments').html("<%= escape_javascript(render(:partial => 'comments/comments')) %>");
  //$('.commentTextArea').val('');

});

app/views/users/handle_post_like_dislike.js.erb
//like button stuff
<% if @current_post.liked_by(current_user) %>
  $('.likeButtonText').html("Liked");

<% else %>
  $('.likeButtonText').html("Like");

<% end %>

$('.postLikes').html("<%= @current_post.likes %>");

//dislike button stuff
<% if @current_post.disliked_by(current_user) %>
  $('.dislikeButtonText').html("Disliked");

<% else %>
  $('.dislikeButtonText').html("Dislike");

<% end %>

$('.postDislikes').html("<%= @current_post.dislikes %>");

app/views/users/handle_sub_unsub.js.erb
$('.subButton').html("<%= escape_javascript(render('users/sub_button')) %>");

$('.profileSubCount').html("<%= @user.followers.count %>");

app/views/users/new.html.erb
<!-- Sign up page -->
<%= provide(:background_image, "memeBackground") %>
<% provide(:title, "Sign Up") %>
<% provide(:subtitle, "We have a table waiting for you") %>

<div class="container-fluid">

  <div class="row">
    <div class="col-md-offset-2 col-sm-offset-2">
      <div>
        <h1 class="signupPageTitle">Welcome to The Meme Kitchen
          <br><small>-The Dankest Meme Restaurant on the Internet</small></h1>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-offset-4 col-md-5 col-sm-offset-3 col-sm-6">
      <div class="signupBlock">

        <h1 style= "color: #676767;">Sign Up</h1>

        <%= form_for @user do |f| %>

          <%= render 'shared/error_messages', object:f.object, style:"position:absolute;" %>

          <%= f.label :name, "Username", style: "color: #676767;" %>
          <%= f.text_field :name, class:"form-control" %><br>

          <%= f.label :email, style: "color: #676767;" %>
          <%= f.email_field :email, class:"form-control" %><br>

          <%= f.label :password, style: "color: #676767;" %>
          <%= f.password_field :password, class:"form-control" %><br>

          <%= f.label :password_confirmation, "Confirm Password", style: "color: #676767;" %>
          <%= f.password_field :password_confirmation, class:"form-control" %><br>

          <%= f.submit "Create Account", class: "btn btn-md btn-danger", style: "float: right; margin-top: -10px; font-weight: bold;" %><br>

        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= provide(:background_image, "profileBackground") %>
<% provide(:title, "Profile") %>
<% provide(:subtitle, "Dank Memer") %>

<!-- notification modals for when users do something (Update profile, make a new post, signup, etc) -->
<%= render 'users/user_modals' %>

<div class="container">

  <div class="row">
    <div class="col-md-offset-1 col-md-11 col-sm-offset-1 col-sm-11">
      <!--Header partial contains the upper block with all of the profile information and functionality -->
      <%= render 'users/user_profile_header' %>
    </div>
  </div>

  <div class="row">

    <div class="userProfilePosts">
      <!-- Partial renders all of the user's posts -->
      <%= render 'users/user_profile_posts' %>
    </div>

  </div>
</div>