config/routes.rb
Rails.application.routes.draw do

  get '/home', to: 'main_courses#home'
  get '/buffet', to: 'static_pages#buffet'
  get '/kitchen', to: 'posts#new'
  get '/users/user_posts_feed', to: 'users#user_posts_feed'
  get '/personal_chefs', to: "static_pages#personal_chefs"
  get '/subscribers', to: 'static_pages#subscribers'
  get '/bar', to: 'static_pages#bar'

  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  post 'application/handle_main_course' => 'application#handle_main_course'

  post 'static_pages/handle_next' => 'static_pages#handle_next'
  post 'static_pages/handle_prev' => 'static_pages#handle_prev'
  post 'static_pages/handle_like' => 'static_pages#handle_like'
  post 'static_pages/handle_dislike' => 'static_pages#handle_dislike'

  post 'main_courses/handle_next' => 'main_courses#handle_next'
  post 'main_courses/handle_prev' => 'main_courses#handle_prev'
  post 'main_courses/handle_like' => 'main_courses#handle_like'
  post 'main_courses/handle_dislike' => 'main_courses#handle_dislike'


  post 'users/handle_next' => 'users#handle_next'
  post 'users/handle_prev' => 'users#handle_prev'
  post 'users/handle_post_like' => 'users#handle_post_like'
  post 'users/handle_post_dislike' => 'users#handle_post_dislike'
  post 'users/handle_subscribe' => 'users#handle_subscribe'
  post 'users/handle_unsubscribe' => 'users#handle_unsubscribe'

  post 'comments/handle_like' => 'comments#handle_like'
  post 'comments/handle_dislike' => 'comments#handle_dislike'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'main_courses#home'

  resources :users do
    member do
     get :posts_feed
    end

    member do
      get :subscribers
    end

    member do
      get :edit_password
    end
  end
  resources :posts
  resources :comments, except: [:show]
  resources :notifications do
    member do
      get :notification_list
    end
  end

  resources :notifications, only: [:delete]

end

app/views/layouts/_sidebar.html.erb
<!--This is the left sidebar menu for the website -->
<div class="sidebar">
    <h1 id="logo"><%= yield(:title) %><br><small style="color: #bbbbbb;"><%= yield(:subtitle) %><br></small></h1>

  <ul class="nav nav-pills nav-stacked">
    <li class="nav-divider"></li>
    <li><%= link_to(home_path) do %>
          <b class="glyphicon glyphicon-star"></b> Main Course</li><% end %>
    <li><%= link_to(buffet_path) do %>
          <b class="glyphicon glyphicon-cutlery"></b> Buffet</li><% end %>
    <% if logged_in? %>
      <li><%= link_to(personal_chefs_path) do %>
            <b class="glyphicon glyphicon-heart"></b> Personal Chefs</li><% end %>
        <li><%= link_to(bar_path) do %>
              <b class="glyphicon glyphicon-glass"></b> Bar</li><% end %>
        <li class="nav-divider"></li>
        <li><%= link_to(kitchen_path) do %>
              <b class="glyphicon glyphicon-fire"></b> Kitchen</li><% end %>
        <li><%= link_to(current_user) do %>
              <% if(current_user.notifications.where(seen: false).count != 0) %><span class="badge"><%= current_user.notifications.where(seen: false).count %></span><% end %><b class="glyphicon glyphicon-user"></b> Profile</li><% end %>
    <% end %>
    <li class="nav-divider"></li>
    <% if logged_in? %>
    <li><%= link_to(logout_path, method: "delete") do %>
          <b class="glyphicon glyphicon-log-out"></b> Logout</li><% end %>
    <% else %>
      <li><%= link_to(login_path) do %>
            <b class="glyphicon glyphicon-log-in"></b> Login</li><% end %>
      <li class="nav-divider"></li>
      <li><%= link_to(signup_path) do %>
            <b class="glyphicon glyphicon-sunglasses"></b> Signup</li><% end %>
    <% end %>

    <li class="nav-divider"></li>
  </ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Meme Kitchen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
  <![endif]-->

  <%= favicon_link_tag("favicon.ico") %>

  </head>

  <body class="<%= yield(:background_image)%>" >

    <!-- Allow flash messages to appear on any page -->
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>" data-dismiss="alert"   style="font-weight: bold; position: absolute; right: 0px; width: 100%; z-index: 1001;">
          <%= message %>
        <a href="#" class="close" style="float:right;">&times;</a>
      </div>
    <% end %>

    <%= render 'layouts/sidebar' %>
    <%= yield %>

  </body>
</html>